#!/bin/sh -e

export PACKAGE="sentry_asgi"
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export VERSION_SCRIPT="import sys; print('%s.%s' % sys.version_info[0:2])"
export PYTHON_VERSION=`python -c "$VERSION_SCRIPT"`

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov=$PACKAGE --cov=tests --cov-report=term-missing ${@}
if [ "${PYTHON_VERSION}" = '3.7' ]; then
    echo "Skipping 'black' on 3.7. See issue https://github.com/ambv/black/issues/494"
else
    ${PREFIX}black $PACKAGE tests --check
fi
${PREFIX}isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --combine-as --line-width 88 --recursive --check-only $PACKAGE tests
